### PR TITLE
Added getUserMedia option style detection

### PR DESCRIPTION
**Pull request by tgvashworth**
Based on work by @miketaylr [here](https://gist.github.com/f2ac64ed7fc467ccdfe3), and me [here](https://gist.github.com/1931422).

Should allow this shim to support browsers with string style or object style options.

### CODE REVIEW

**Comment by addyosmani** [comment]
Great work, @phuu!. I'll be doing some testing on this this afternoon just to confirm the demos still play nice, but otherwise the PR is looking solid. Should be able to merge today. Thanks!.

**Comment by tgvashworth** [comment]
Cheers.

I should say, I've tested in the Opera Labs Camera build, Opera Next 12.0.0, Opera 11.61, Chrome 17.0.963.79, Chrome Canary 19.0.1067.0 and Firefox 10.0.2 all on OSX Lion. I woulda done IE, but I don't have my external drive with the VMs on it!

**Comment by addyosmani** [comment]
Very useful to know! Cheers. I'll get the IE testing out of the way and cover testing on Windows + Leopard for the others.

**Comment by addyosmani** [comment]
Thanks for this again @phuu!

**Pull request merged**
